apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-customer-service
  namespace: backend
  labels:
    app: my-customer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-customer-service
  template:
    metadata:
      labels:
        app: my-customer-service
    spec:
      containers:
        - name: customer-backend
          image: sksamy1990/my-micro-srv-customer:v2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-customer-service
  namespace: backend
spec:
  selector:
    app: my-customer-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
