apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-customer-to-postgres
  namespace: db
spec:
  podSelector:
    matchLabels:
      app: postgres-db
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: backend
          podSelector:
            matchLabels:
              app: my-customer-service
      ports:
        - protocol: TCP
          port: 5432
  policyTypes:
    - Ingress
