apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-fe-app
  namespace: frontend
  labels:
    app: my-react-fe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-fe-app
  template:
    metadata:
      labels:
        app: my-react-fe-app
    spec:
      containers:
        - name: react-frontend
          image: sksamy1990/my-react-fe-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-fe-service
  namespace: frontend
spec:
  selector:
    app: my-react-fe-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
