apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-react-fe-ingress
  namespace: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: my-react-app.local  # Replace with your domain or local DNS setup
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-react-fe-service
                port:
                  number: 80
